import type { Metadata } from "next";
import "./globals.css";
// import Header from "./components/Header";
import Footer from "./components/Footer";
import { ReactQueryClientProvider } from "@/components/providers";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "DoQuanta - Your AI Powered Task Manager",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          {/* <Header/> */}
          {children}
          <Footer/>
          <Toaster position="bottom-right" />
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
